export const CLEANUP = 'CLEANUP';

export const LIST_SUGGESTIONS_BY_STORE_REQUEST =
  'LIST_SUGGESTIONS_BY_STORE_REQUEST';
export const LIST_SUGGESTIONS_BY_STORE_SUCCESS =
  'LIST_SUGGESTIONS_BY_STORE_SUCCESS';
export const LIST_SUGGESTIONS_BY_STORE_ERROR =
  'LIST_SUGGESTIONS_BY_STORE_ERROR';
