export const CLEANUP = 'CLEANUP';

export const LIST_SUGGESTIONS_BY_STORE_REQUEST =
  'GET_SUGGESTIONS_BY_STORE_REQUEST';
export const LIST_SUGGESTIONS_BY_STORE_SUCCESS =
  'GET_SUGGESTIONS_BY_STORE_SUCCESS';
export const LIST_SUGGESTIONS_BY_STORE_ERROR = 'GET_SUGGESTIONS_BY_STORE_ERROR';
