export const FETCH_SELLERS_REQUEST = 'FETCH_SELLERS_REQUEST';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_ERROR = 'FETCH_SELLERS_ERROR';

export const FETCH_SELLER_REQUEST = 'FETCH_SELLER_REQUEST';
export const FETCH_SELLER_SUCCESS = 'FETCH_SELLER_SUCCESS';
export const FETCH_SELLER_ERROR = 'FETCH_SELLER_ERROR';

export const FETCH_SELLER_PRODUCTS_REQUEST = 'FETCH_SELLER_PRODUCTS_REQUEST';
export const FETCH_SELLER_PRODUCTS_SUCCESS = 'FETCH_SELLER_PRODUCTS_SUCCESS';
export const FETCH_SELLER_PRODUCTS_ERROR = 'FETCH_SELLER_PRODUCTS_ERROR';
