export const CLEANUP = 'CLEANUP';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST';
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS';
export const LIST_PRODUCTS_ERROR = 'LIST_PRODUCTS_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const LIST_STORE_PRODUCTS_REQUEST = 'LIST_STORE_PRODUCTS_REQUEST';
export const LIST_STORE_PRODUCTS_SUCCESS = 'LIST_STORE_PRODUCTS_SUCCESS';
export const LIST_STORE_PRODUCTS_ERROR = 'LIST_STORE_PRODUCTS_ERROR';
