export const GET_STORE_REQUEST = 'GET_STORE_REQUEST';
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_ERROR = 'GET_STORE_ERROR';

export const GET_STORES_REQUEST = 'LIST_STORES_REQUEST';
export const GET_STORES_SUCCESS = 'LIST_STORES_SUCCESS';
export const GET_STORES_ERROR = 'LIST_STORES_ERROR';

export const GET_STORE_PRODUCTS_REQUEST = 'LIST_STORE_PRODUCTS_REQUEST';
export const GET_STORE_PRODUCTS_SUCCESS = 'LIST_STORE_PRODUCTS_SUCCESS';
export const GET_STORE_PRODUCTS_ERROR = 'LIST_STORE_PRODUCTS_ERROR';
