export const ORDERS_CLEANUP = 'ORDERS_CLEANUP';
export const SET_ORDERS = 'SET_ORDERS';

export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST';
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS';
export const LIST_ORDERS_ERROR = 'LIST_ORDERS_ERROR';

export const UPDATE_ORDERS_REQUEST = 'UPDATE_ORDERS_REQUEST';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_ERROR = 'UPDATE_ORDERS_ERROR';
